### ISSUE TITLE
Advancing past stage1

### ISSUE THREAD

**Issue by panekj** [chainguard-dev/wolfi-bootstrap-stage1#1]
Below code is a fix for limited `limits.h` header (glibc-only) according to https://stackoverflow.com/questions/58199020/locally-built-gcc-cross-compiler-reports-mb-len-max-wrong-with-d-fortify-source
`cd build` should be dropped `gcc/*` is in source not in `build/`
https://github.com/chainguard-dev/inky-bootstrap-stage1/blob/7127228fce414955c449d5da9af240eade0320e2/cross-gcc.yaml#L80-L92

Problem is that `mkheaders` fails to `cd` to some dir when given `${{targets.destdir}}/usr`

step looks something like:
```yaml
  - runs: |
      /usr/libexec/gcc/$(uname -m)-pc-linux-gnu/11.3.0/install-tools/mkheaders -v /usr
```

I can't get anywhere past that, tried with making `cross-m4` following LFS but getting same error as mentioned in SO post

```yaml
package:
  name: m4
  version: 1.4.19
  epoch: 0
  description: "GNU macro processor"
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: TODO
      license: bzip2-1.0.6
  dependencies:
    runtime:

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
    packages:
      - busybox
      - ssl_client
      - ca-certificates-bundle
      - cross-gcc-stage1
      - cross-binutils-stage1
      - cross-glibc-stage1
      - cross-libstdc++-stage1
      - cross-linux-headers

pipeline:
  - uses: fetch
    with:
      uri: https://ftp.gnu.org/gnu/m4/m4-${{package.version}}.tar.gz
      expected-sha256: 3be4a26d825ffdfda52a56fc43246456989a3630093cced3fbddf4771ee58a70
  - name: Fix
    runs: |
        ln -s /usr/bin/x86_64-pc-linux-gnu-as /usr/bin/as
        ln -s /usr/bin/x86_64-pc-linux-gnu-ld /usr/bin/ld
        ./configure \
          --prefix=/usr \
          --host=$(uname -m)-pc-linux-gnu
  - uses: autoconf/make
  - uses: autoconf/make-install
```
